name: Update Readme

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: thansetan/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: "thansetan-waka"
          SHOW_UPDATED_DATE: true
          SHOW_TOTAL_CODE_TIME: true
          SHOW_PROFILE_VIEWS: false
          SHOW_OS: false
          SHOW_PROJECTS: false
          SHOW_TIMEZONE: false
          SHOW_EDITORS: true
          SHOW_LOC_CHART: false
          IGNORED_REPOS: "penghijauan"
          INCLUDE_PRIVATE: false
          WAKA_STATS_PERIOD: all
